#!/usr/bin/env bash
# return 404 error_page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "
server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html;

    server_name 34.207.211.110;

    error_page 404 /404.html;
    location = /404.html {
        internal;
        return 404 'Ceci n\'est pas une page';
    }
}
" > /etc/nginx/sites-available/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
