#!/usr/bin/env bash
# install and configure HAproxy

#update and install haproxy
apt-get update -y
apt-get install -y haproxy

#enable managing haproxy via an init script
sed -i "s/ENABLED=0/ENABLED=1" /etc/default/haproxy

#backup haproxy config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

MY_ID=172792

#configuration the two servers using roundrobins algorithm
echo "
listen $MY_ID-lb-01
    bind *:80
    balance roundrobin
    server $MY_ID-web-01 34.207.211.110:80 check
    server $MY_ID-web-02 54.152.234.206:80 check
" >> /etc/haproxy/haproxy.cfg

# restart haproxy
service haproxy restart
