#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

# Update the package list and Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo sed -i "s/.*ENABLED=.*/ENABLED=1/" /etc/default/haproxy
sudo touch /etc/haproxy/haproxy.cfg
sudo chmod 666 /etc/haproxy/haproxy.cfg
sudo cat > /etc/haproxy/haproxy.cfg <<EOF

frontend load_balancer
    bind 172792-lb-01:80
    mode http
    default_backend web_servers


backend web_servers
    mode http
    balance roundrobin
    server web-01 172792-web-01:80 check
    server web_02 172792-web-02:80 check
EOF

#MAke sure HAproxy can be managed via an init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy
