#!/usr/bin/env bash
# write the same bash script in task 0 but in a shorter way <= 5lines
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
