#!/usr/bin/env bash
# write the same bash script in task 0 but in a shorter way <= 5lines
service nginx status | grep -q "not running" || service nginx restart
grep -q "listen\s\+80" /etc/nginx/sites-enabled/* || sed -i '/server {/a \    listen 80;' /etc/nginx/sites-enabled/default
service nginx restart
