#!/usr/bin/env bash
#displays "Best School" 10 times but the 9th iter, print "Best Schhol""Hi"

counter=1

while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ] ; then
		echo "Hi"
	fi
	counter=$((counter+1))
done
