#!/usr/bin/env bash
#docker

docker run -p 8080:80 -d -it holbertonschool/265-0
docker ps
docker exec -it <container-id> /bin/bash
service apache2 status
service apache2 start
vi /var/www/html/index.html
# update the contents of the index.html file
exit
